using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Linq;

namespace generator {

[AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
public class GenerateToStringAttribute : Attribute { }

[Generator]
public class ToStringGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Step 1: Select classes with [GenerateToString] attribute
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: (ctx, _) =>
                {
                    var classSymbol = ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol;
                    bool hasAttribute = classSymbol?.GetAttributes()
                        .Any(a => a.AttributeClass?.Name == "GenerateToStringAttribute") ?? false;
                    return hasAttribute ? (ctx.Node as ClassDeclarationSyntax, ctx.SemanticModel) : (null, null);
                })
            .Where(tuple => tuple.Item1 != null);

            Console.WriteLine(classDeclarations.GetType().Name);

        // Step 2: Generate code for each selected class
        context.RegisterSourceOutput(classDeclarations, (spc, tuple) =>
        {
            var (classSyntax, semanticModel) = tuple;
            if (classSyntax == null || semanticModel == null) return;

            var classSymbol = semanticModel.GetDeclaredSymbol(classSyntax) as INamedTypeSymbol;
            if (classSymbol == null) return;

            string namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
            string className = classSymbol.Name;

            // Generate the ToString method
            string source = $$"""
                // <auto-generated/>
                namespace {{namespaceName}}
                {
                    partial class {{className}}
                    {
                        public override string ToString() => "Generated ToString for {{className}}";
                    }
                }
                """;

                Console.WriteLine(source);

            spc.AddSource($"{className}.g.cs", source);
        });
    }
}
}