using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Diagnostics;

namespace generator
{

    [Generator]
    public class ToStringGenerator : IIncrementalGenerator
    {
        string AttributeName = "shared.GenerateToStringAttribute";
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
#if DEBUG
            if (!Debugger.IsAttached)
                Debugger.Launch();
#endif

            IncrementalValuesProvider<InspectedClassModel> classDeclarations = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    fullyQualifiedMetadataName: AttributeName,
                    predicate: static (node, _) => node is ClassDeclarationSyntax, // Syntactic filter
                    transform: static (ctx, _) => TransformTarget(ctx))           // Semantic transform
                .Where(static m => m is not null)!;

            context.RegisterSourceOutput(classDeclarations, static (spc, classModel) => Execute(spc, classModel));
        }

        private static InspectedClassModel? TransformTarget(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol)
                return null;

            // Retrieve the specific attribute data that triggered this match
            AttributeData? attributeData = ctx.Attributes.FirstOrDefault();
            if (attributeData == null)
                return null;

            // Extract values from Constructor Arguments (e.g., [MyCustom("SomeValue")])
            string positionalArg = attributeData.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? "";

            // Extract values from Named Properties (e.g., [MyCustom(MyProperty = "SomeValue")])
            string formatValue = attributeData.NamedArguments
                .FirstOrDefault(x => x.Key == "Format").Value.Value?.ToString() ?? "";

            return new InspectedClassModel(classSymbol.Name, classSymbol.ContainingNamespace.Name, formatValue);
        }

        private static void Execute(SourceProductionContext context, InspectedClassModel model)
        {
            // Generation logic using the values extracted from the attribute
            var source = $$"""
                    // <auto-generated/>
                    namespace {{model.NamespaceValue}}
                    {
                        public partial class {{model.ClassName}}
                        {
                            public override string ToString() => "Generated ToString for {{model.ClassName}}";
                        }
                    }
                    """;
            context.AddSource($"{model.ClassName}.g.cs", source);
        }
    }
    public record InspectedClassModel(string ClassName, string NamespaceValue, string AttrFormatValue);
}
namespace System.Runtime.CompilerServices
{
    internal static class IsExternalInit { }
}