using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Diagnostics;
using System.Text;

namespace generator
{

    [Generator]
    public class ToStringGenerator : IIncrementalGenerator
    {
        string AttributeName = "shared.GenerateToStringAttribute";
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
#if DEBUG
            if (!Debugger.IsAttached)
                Debugger.Launch();
#endif

            IncrementalValuesProvider<InspectedClassModel> classDeclarations = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    fullyQualifiedMetadataName: AttributeName,
                    predicate: static (node, _) => node is ClassDeclarationSyntax, // Syntactic filter
                    transform: static (ctx, _) => TransformTarget(ctx))           // Semantic transform
                .Where(static m => m is not null)!;

            context.RegisterSourceOutput(classDeclarations, static (spc, classModel) => Execute(spc, classModel));
        }

        private static InspectedClassModel? TransformTarget(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol)
                return null;

            // Retrieve the specific attribute data that triggered this match
            AttributeData? attributeData = ctx.Attributes.FirstOrDefault();
            if (attributeData == null)
                return null;


            // Extract values from Constructor Properties (e.g., [MyCustom("SomeValue", "OtherValue")])
            string formatValue = attributeData.ConstructorArguments[0].Value?.ToString() ?? "";
            var argNamesValues = attributeData.ConstructorArguments[1].Values;
            var propertyNames = new string [argNamesValues.Length];
            var i = 0;
            foreach (var propertyName in argNamesValues)
            {
                propertyNames[i] = (string) argNamesValues[i++].Value;
            }

            return new InspectedClassModel(classSymbol.Name, classSymbol.ContainingNamespace.Name, formatValue, propertyNames);
        }

        private static void Execute(SourceProductionContext context, InspectedClassModel model)
        {
            // Generation logic using the values extracted from the attribute
            var sb = new StringBuilder();
            foreach (var argName in model.AttrArgNames)
                sb.Append(argName).Append(", ");
            if (model.AttrArgNames.Length > 0)
                sb.Remove(sb.Length - 2, 2);

            var source = $$"""
                    // <auto-generated/>
                    namespace {{model.NamespaceValue}}
                    {
                        public partial class {{model.ClassName}}
                        {
                            public override string ToString() => string.Format("{{model.AttrFormatValue}}", {{sb.ToString()}});
                        }
                    }
                    """;
            context.AddSource($"{model.ClassName}.g.cs", source);

            /*
             the expected output:

            ::Person.g.cs

            public partial class Person
            {
                public override string ToString() => string.Format("{0} ({1}) e-mail: {2}", Name, Age, Email);
            }

             */
        }
    }
    public record InspectedClassModel(
        string ClassName,
        string NamespaceValue,
        string AttrFormatValue,
        string[] AttrArgNames);
}

// A stupid fix for Microsoft's lack of skill. This fix is "officially" recommended for netstandard2.0 projects
// if you want to enable record and init features. 
namespace System.Runtime.CompilerServices
{
    internal static class IsExternalInit { }
}